### PR TITLE
fix deprecated lifecycles

### LINKED ISSUE #35: Deprecated lifecycle hooks are being used in material-ui-image
componentWillReceiveProps is deprecated and will be removed from the next major release of React while they are being used by Image.

I'm using material-ui-image@^3.2.0 and react@^16.9.0

Any page that uses Image shows the following warning:
image

### PR DESCRIPTION
**Pull request by ahmad-reza619**
Closes #35 

i have replaced the deprecated method with the new one, btw this is my first contrib 😄

### CODE REVIEW

File: src/components/Image/Image.js [hunk 1]
```diff
@@ -18,12 +18,12 @@ export default class Image extends Component {
     }
   }
 
-  componentWillReceiveProps (nextProps) {
-    if (this.props.src !== nextProps.src) {
-      this.setState({
+  static getDerivedStateFromProps(nextProps) {
+    if (this.props.src !== nextProps.src){
```
Comment (leMaik) [inline src/components/Image/Image.js]: Since `getDerivedStateFromProps` is static, you can't use `this` here. The current `src` would need to be moved into the state and then you can use `currentState` (the second argument of `getDerivedStateFromProps` to check if it changed.

Comment (ahmad-reza619) [reply src/components/Image/Image.js]: oh right, thanks for the tips

**Comment by ahmad-reza619** [comment]
Okay i have made changes based on your suggestions 👍
